config/routes.rb
Rails.application.routes.draw do
  resources :reculutements, only:[:index, :create, :edit, :update]
  resources :participants, only:[:index]
  resources :promises, only:[:new, :create, :index, :show]
  resource  :user, only:[:new, :show, :edit, :update]

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get "top/create_user"
  get "top/contract"
  get "top/privacy_policy"
  root 'top#index'

  scope :user do
    resources :tasks
  end
end

app/models/promise.rb
class Promise < ActiveRecord::Base
  belongs_to :user
  has_many :reculutement

  validates :title, presence: true
  validates :content, presence: true
  validate :before_limit_time

  mount_uploader :image, ImageUploader

  def before_limit_time
    if limit_time > promise_time
      errors.add(:ride_mount, "締切日より前に設定してください")
    end
  end

  def self.my_build_promise(user)
    promises = Promise.where(user_id: user.id)
  end

  def self.your_build_promise(user)
    reculutements = user.reculutements
    promises = reculutements.map { |reculutement| reculutement.promise }
  end

  def self.decide_promise(user)
      promises = user.promises
      promises = promises.joins(:reculutement).where("reculutements.result = true")
  end

  def self.my_promises(user)
    reculutements = user.reculutements.where(result: true)
    my_promises = reculutements.map { |reculutement| reculutement.promise }
  end

  def self.my(params)
    params == nil || params == "my"
  end

  def self.your(params)
    params == "your"
  end

  def self.cheeeeeck(params)
    params == "cheeeeeck"
  end

  def self.check_promise(params = nil, user)
    if my(params)
      my_build_promise(user)
    elsif your(params)
      your_build_promise(user)
    elsif cheeeeeck(params)
      decide_promise(user)
    end
  end
end

app/models/reculutement.rb
class Reculutement < ActiveRecord::Base
  belongs_to :promise
  belongs_to :user

  scope :participations_all, ->(user) {
    joins(promise: :user)
    .select('users.id')
    .where('participation_id = ?', user)
  }
  scope :applicant, -> { where.not(result: false) }

  def self.decide_mountain(params, id)
    # 参加希望者のid
    user = params[:id]
    promise = Promise.find_by(user_id: id)
    a = promise.reculutement.first
    resulut = params[:result]
    a.update(result: true) if resulut == "ok"
    a.update(result: false) if resulut == "no"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :promises
  has_many :reculutements

  mount_uploader :image, ProfileImageUploader

  def self.get_participations(user)
    promises_id = Promise.where(user_id: user.id).pluck(:id)
    reculutements_user_id = Reculutement.where(promise_id: promises_id).pluck(:user_id)
    User.find(reculutements_user_id)
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          provider:  auth.provider,
          uid:       auth.uid,
          email:     auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url: auth.info.image,
          gender:    auth.extra.raw_info.gender,
          password:  Devise.friendly_token[0, 20]
      )

      user.save(validate: false)
    end
    user
  end

  def already_joined_promise(promise)
    reculutements.where(promise_id: promise.id)
  end

  def joined?(promise)
    already_joined_promise(promise).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_user!
  def index
    @promises = Promise.check_promise(params[:name], current_user)
    @my_promises = Promise.my_promises(current_user) if Promise.cheeeeeck(params[:name])
  end
end

app/controllers/promises_controller.rb
class PromisesController < ApplicationController
  before_action :authenticate_user!
  def index
    @promises = Promise.where.not(user_id: current_user.id)
  end

  def new
    @promise = Promise.new
  end

  def show
    @promise = Promise.find(params[:id])
  end

  def create
    @promise = current_user.promises.build(params_promise)

    if @promise.save
      redirect_to user_path, notice: "登山日を登録しました！"
    else
      render :new
    end
  end

  private

  def params_promise
    params.require(:promise).permit(:promise_time, :meet_time, :title, :content, :limit_time)
  end
end

app/controllers/reculutements_controller.rb
class ReculutementsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.get_participations(current_user)
  end

  def show
    #code
  end

  def create
    @reculutement = current_user.reculutements.build(
                    promise_id: params[:promise_id],)
    @reculutement.save
    redirect_to user_path, notice: "一緒に行けるといいですね"
  end

  def edit
    redirect_to :update
  end

  def update
    Reculutement.decide_mountain(params, current_user.id)
    redirect_to user_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @user = User.new
    render :index, layout: 'landing_layout'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def after_sign_in_path_for(resource)
    if resource.name.blank?
      new_user_path
    else
      user_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:new, :show, :edit, :update]

  def new
  end

  def show
    @promises = Promise.all
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :image, :birthday, :self_introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_helper.rb
module CommonHelper
  def get_promise_image(image)
    if image.present?
      image
    else
      'no-image.png'
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def get_user_name(name)
    if name.blank?
      "名前はまだない"
    else
      name
    end
  end

  def get_image(user)
    if user.image.blank?
      'default_prof.png'
    else
      user.image
    end
  end

  def get_self_introduction(user)
    if user.self_introduction.blank?
      link_to 'なにかひとことを入れてみよう', edit_user_path
    else
      user.self_introduction
    end
  end

  def calc_age(birthday)
    (Date.today.strftime("%Y%m%d").to_i - birthday.strftime("%Y%m%d").to_i) / 10000
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mt.Takao</title>
    <%= stylesheet_link_tag 'landing/application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <div id="fh5co-wrapper">
      <div id="fh5co-page">
        <%= render partial: 'shared/landing/header' %>
        <%= yield %>
        <%= render partial: 'shared/landing/footer' %>
      </div>
    </div>
    <%= javascript_include_tag 'landing/application' %>
  </body>
</html>

app/views/layouts/landing_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mt.Takao</title>
    <%= stylesheet_link_tag 'landing/application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="fh5co-wrapper">
      <div id="fh5co-page">
      
        <%= yield %>

      </div>
    </div>  
    <%= javascript_include_tag 'landing/application' %>
  </body>
</html>

app/views/mount_users/edit.html.slim
.verify
  .verify__menu
    .verify__form
      .verify__form__container
        h2.verify__title ユーザ情報編集
        = form_for @user, url: mount_user_path(@user)  do |f|
          .verify__field
            = f.label :name, class: 'form__label'
            = f.text_field :name, class: 'form__text__box'
          .verify__field
            = f.label :image, class: 'form__label'
            = image_tag @user.image if @user.image?
            = f.file_field :image, class: 'form__text__box'
            = f.hidden_field :image_cache
          .verify__field
            = f.label :one_thing, class: 'form__label'
            = f.text_field :one_thing, class: 'form__text__box'
          .verify__action
            = f.submit "編集する", class: 'devise_btn'

    .verify__description
      h2.verify__title 高尾山とは
      p.verify__takao__msg 
        | 高尾山は、東京都八王子市にある標高599mの山である。東京都心から近く、年間を通して多くの観光客や登山者が訪れる。古くから修験道の霊山とされた。
        br  
        | (出典：ウィキペディア)

app/views/participants/_list.html.slim
ul.media-list
  - promises.each do |promise|
    li.media.list-item
      = link_to promise_path(promise), class: 'media-left'
                  = image_tag promise.image, class: 'image-sm'
      .media-body
        h4.media-heading = promise.title
        p.list-text = "登山日: #{l(promise.promise_time, format: :promise)}"
        p.list-text = "募集締切: #{l(promise.limit_time, format: :promise)}"

app/views/participants/index.html.slim
.l-container
  .participant__select__area
    = link_to "確定した登山", { name: "cheeeeeck" }, class: 'form__btn participant__btn'
    = link_to "主催一覧", { name: "my" }, class: 'form__btn participant__btn'
    = link_to "参加一覧(予定も含むよ！)", { name: "your" }, class: 'form__btn participant__btn'
  ul.default__list
    - if @promises.present?
      - @promises.each do |promise|
        li.default__list__item.participant__list__item
            p.list__profile__info__text
              'イベント名：
              = promise&.title
            p.list__profile__info__text
              'イベント内容：
              = promise&.content
            p.list__profile__info__text
              = promise&.promise_time&.strftime('%Y年%m月%d日 %H:%M:%S')
    - if @my_promises.present?
      - @my_promises.each do |my_promise|
        li.default__list__item.participant__list__item
            p.list__profile__info__text
              'イベント名：
              = my_promise&.title
            p.list__profile__info__text
              'イベント内容：
              = my_promise&.content
            p.list__profile__info__text
              = my_promise&.promise_time&.strftime('%Y年%m月%d日 %H:%M:%S')
            p.list__profile__info__text
  = render 'shared/link'

app/views/participants/index.js.erb
$('##participants_list').html(<%= j render partial: 'participants/list', locals: { promises: @promises } %>);

app/views/participation_users/index.html.slim
- @participation_users.each do |user|
  = user.name
= render 'shared/link'

app/views/promises/index.html.slim
.l-container
  h2.promise__title 募集している人
  ul.default__list
    - @promises.each do |promise|
      li.default__list__item
        .list__profile
          = image_tag get_image(promise.user), class: 'list__profile__image'
        .list__profile__info
          p.list__profile__info__subject
            = promise&.title
          p.list__profile__info__text
            = get_user_name(promise.user&.name)
          p.list__profile__info__text
            = l(promise.promise_time, format: :promise)
          - if current_user.joined?(promise)
            p この募集は登録済みです
          - else
            = button_to '一緒に登りたい', reculutements_path, params: { user_id: promise.user.id, promise_id: promise.id }, class: 'form__btn promise__button'

  = render 'shared/link'

app/views/promises/new.html.slim
.l-container
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading 山に登る日にちを決めよう
        .panel-body
          = form_for @promise do |f|
            - if @promise.errors.any?
              .panel.panel-danger.error-panel
                p.error-title = "#{@promise.errors.count}つのエラーがあります"
                ul
                  - @promise.errors.full_messages.each do |message|
                    li.error-text = message
            .field
              = f.label :title
              = f.text_field :title, class: 'form-control'
            .field
              = f.label :promise_time
              = f.date_field :promise_time, class: 'form-control'
            .field
              = f.label :limit_time
              = f.date_field :limit_time, class: 'form-control'
            .field
              = f.label :image
              = image_tag @promise.image if @promise.image?
              = f.file_field :image
              = f.hidden_field :image_cache
            .field
              = f.label :content
              = f.text_area :content, class: 'form-control lg'
            .field
              = link_to 'ホームへ戻る', user_path, class: 'btn btn-default'
              = f.submit "編集する", class: 'btn btn-success mgl-10'

app/views/promises/show.html.slim
.l-container
  .row
    .col-md-3
      .panel.panel-default.profile-area
        = image_tag get_image(@promise.user), class: 'profile-image'
        p.profile-name
          = @promise.user.name + " (#{calc_age(@promise.user.birthday)})"
        .field
          = simple_format get_self_introduction(@promise.user)
      = link_to 'マイページに戻る', user_path, class: 'btn btn-default'
    .col-md-9
      h2 = @promise.title
      .field
        = image_tag get_promise_image(@promise.image), class: 'img-responsive promise-image'
      hr
      .field
        table.table
          thead
            tr
              th 登山日
              th 募集締切
          tbody
            tr
              td = l(@promise.promise_time, format: :promise)
              td = l(@promise.limit_time, format: :promise)
      hr
      .field
        label 募集詳細
        = simple_format @promise.content

app/views/reculutements/index.html.slim
.l-container
  h2.promise__title あなたの募集の希望者
  ul.default__list
    - @users.each do |reculutement|
      li.default__list__item
        .list__profile
          = image_tag get_image(reculutement), class: 'list__profile__image'
        .list__profile__info
          p.list__profile__info__text
            'ユーザ名：
            = get_user_name(reculutement.name)
          p.list__profile__info__text ひとこと：よろしくお願いします！
        .reculutement__btn__area
          = link_to "一緒に登る", reculutement_path(reculutement, result: "ok"), method: :put, class: 'form__btn reculutement__btn'
          = link_to "拒否", reculutement_path(reculutement, result: "no"), method: :put, class: 'form__btn reculutement__btn'
  = render 'shared/link'

app/views/shared/_header.html.slim
header.l-header
  h1.header__logo= link_to "Mt.takao", root_path
  = notice
  ul.header__nav
    - if user_signed_in?
      li.header__nav__item = link_to 'ログアウト', destroy_user_session_path, method: :delete
      li.header__nav__item = link_to 'マイページ', user_path
      li.header__nav__item = link_to '待ち合わせ'
    - else
      li.header__nav__item = link_to "作った人", top_create_user_path
      
  - if user_signed_in?
    #ham__menu__btn.header__ham__btn ≡
    ul.header__ham__menu
      li.header__ham__item = link_to 'マイページ', user_path
      li.header__ham__item = link_to '待ち合わせ'
      li.header__ham__item = link_to 'ログアウト', destroy_user_session_path, method: :delete

app/views/shared/_link.html.slim
.user_back
  = link_to "ホームへ戻る", user_path

app/views/shared/landing/_footer.html.erb
<footer>
  <div id="footer">
    <div class="container">
      <div class="row row-bottom-padded-md">
        <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
          <h3>規約</h3>
          <ul>
            <li><%= link_to '利用規約', top_contract_path %></li>
            <li><%= link_to 'プライバシーポリシー', top_privacy_policy_path %></li>
          </ul>
          <p>Copyright 2016 Mt.takao. All Rights Reserved.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
          <!-- <p class="fh5co-social-icons">
            <a href="#"><i class="icon-twitter2"></i></a>
            <a href="#"><i class="icon-facebook2"></i></a>
            <a href="#"><i class="icon-instagram"></i></a>
            <a href="#"><i class="icon-dribbble2"></i></a>
            <a href="#"><i class="icon-youtube"></i></a>
          </p> -->
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/top/create_user.html.slim
.create_user_main_container
  .create_user_main_container_info
    h1.create_user_name 製作者名: miyaoka
    p エンジニア(1年生)
    .create_user_main_image
      = image_tag "menma.jpg"
    ul.create_user_profile
      li 趣味: 開発
      li 好きな山: 石鎚山
      li 好きなこと: 釣り動画を見る
    .create_user_main_description
  .create_user_main_container_info
    h1.create_user_name 製作者名: k村
    p エンジニア
    .create_user_main_image
      = image_tag "kmura.jpeg"
    ul.create_user_profile
      li 趣味: 秘密
      li 好きな山: 秘密
      li 決め球: スライダー
    .create_user_main_description

app/views/top/index.html.erb
<%= render partial: 'shared/landing/header' %>

<div class="fh5co-hero">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-cover text-center main-visual" data-stellar-background-ratio="0.5">
    <div class="desc">
      <div class="container">
        <div class="col-md-12">
          <div class="animate-box">
            <h2>あの日登った高尾はここにある</h2>
            <%= link_to omniauth_authorize_path(@user, 'facebook'), class: 'fb_btn' do %>
              facebookではじめる
            <% end %>
            <!-- <p><a class="btn btn-primary btn-lg" href="#">Get Started</a></p> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="fh5co-feature-product" class="fh5co-section-gray">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
        <h3>山に登りたい山ぼっちに捧ぐ..</h3>
        <p>ヘイ！そこの君！山に登りたくてそわそわしているだろ？そんな君たちを僕らは山ぼっちと呼んでいるんだ。山でいろんな出会いが待っている。そう、あの山が君を待っている</p>
      </div>
    </div>

    <div class="row row-bottom-padded-md">
      <div class="col-md-12 text-center animate-box">
        <p> <%= image_tag "landing/momiji.JPG", class: "img-responsive img-rounded img-responsive img-rounded" %></p>
      </div>

    </div>
    <div class="row row-bottom-padded-md">
      <div class="col-md-4">
        <div class="feature-text">
          <h3>手始めに高尾山に登る</h3>
          <p>都心からアクセスもよく登りやすい山です</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="feature-text">
          <h3>登山者に挨拶をする</h3>
          <p>道行く人はみんな仲間です。先人たちに挨拶をしましょう</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="feature-text">
          <h3>温泉で疲れを取る</h3>
          <p>今日はみんなくたくただろ？駅の横にある温泉で疲れを取るといいよ</p>
        </div>
      </div>
    </div>

    <!-- <div class="row">
      <div class="col-md-12 text-center">
        <a href="https://www.youtube.com/watch?v=Kig9opGTxKE" class="link-watch popup-vimeo btn btn-primary"><i class="icon-play3"></i> Watch our video</a>
      </div>
    </div> -->

  </div>
</div>

<div id="fh5co-portfolio" class="fh5co-section-gray">
  <div class="container">

    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
        <h3>Our Gallery</h3>
        <p>見てみろよ、お前ら。こんなにもすごい景色が見えるんだぜ。まだもたもたしているお前らに少し山の風景を見せてやるぜ。</p>
      </div>
    </div>


    <div class="row row-bottom-padded-md">
      <div class="col-md-12">
        <ul id="fh5co-portfolio-list">

          <li class="two-third animate-box session_kindan">
            <a href="#" class="color-3">
              <div class="case-studies-summary">
                <span>sessionkinndan</span>
                <h2>殺生禁断</h2>
              </div>
            </a>
          </li>

          <li class="one-third animate-box start_line">
            <a href="#" class="color-4">
              <div class="case-studies-summary">
                <span>Beginning town</span>
                <h2>始まりの街</h2>
              </div>
            </a>
          </li>

          <li class="one-third animate-box yamamiti">
            <a href="#" class="color-5">
              <div class="case-studies-summary">
                <span>Mountain path</span>
                <h2>山道</h2>
              </div>
            </a>
          </li>
          <li class="two-third animate-box onsenn">
            <a href="#" class="color-6">
              <div class="case-studies-summary">
                <span>Hot spring</span>
                <h2>温泉</h2>
              </div>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="fh5co-content-section">
  <div class="container">
    <div class="row row-bottom-padded-md">
      <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
        <h3>Our Team</h3>
        <p>エンジニアチーム</p>
      </div>
    </div>
  </div>
  <div class="container">

    <div class="row">
      <div class="col-md-4">
        <div class="fh5co-team text-center animate-box">
          <figure>
            <%= image_tag "landing/seiya.jpg" %>
          </figure>
          <p>seiya miyaoka<br> <span class="text-mute">Developer</span></p>
          <blockquote>
            <p>hahaha ilove TKO</p>
          </blockquote>


        </div>
      </div>
      <div class="col-md-4">
        <div class="fh5co-team text-center animate-box">
          <figure>
            <%= image_tag "landing/kmura.jpeg" %>
          </figure>
          <p>kmura<br> <span class="text-mute">Developer</span></p>
          <blockquote>
            <p>touhoku Developer</p>
          </blockquote>

        </div>
      </div>
      <div class="col-md-4">
        <div class="fh5co-team text-center animate-box">
          <figure>
            <%= image_tag "landing/kitamura.jpg" %>
          </figure>
          <p>kitamura<br> <span class="text-mute">Photographer</span></p>
          <blockquote>
            <p>im enginner & desinger & photographer</p>
          </blockquote>

        </div>
      </div>
    </div>
  </div>
</div>
<!-- fh5co-content-section -->
  </div>
</div>

<%= render partial: 'shared/landing/footer' %>

app/views/users/show.html.slim
.l-container
  .row
    .col-md-3
      .panel.panel-default.profile-area
        = image_tag get_image(@user), class: 'profile-image'
        p.profile-name
          = @user.name + " (#{calc_age(@user.birthday)})"
        .field
          = simple_format get_self_introduction(@user)
        .field
          ul.menu-list
            = link_to edit_user_path(@user) do
              li.menu-list-item
                span.glyphicon.glyphicon-user
                'プロフィール編集 
            = link_to new_promise_path do
              li.menu-list-item
                span.glyphicon.glyphicon-picture
                '待ち合わせ募集
            = link_to promises_path do
              li.menu-list-item
                span.glyphicon.glyphicon-exclamation-sign
                '待ち合わせ確認
    .col-md-9
      .panel.panel-default
        .panel-heading 待ち合わせ
        .panel-body
          ul.media-list
            - @promises.each do |promise|
              li.media.list-item
                = link_to promise_path(promise), class: 'media-left'
                  = image_tag promise.image, class: 'image-sm'
                .media-body
                  h4.media-heading = promise.title
                  p.list-text = "登山日: #{l(promise.promise_time, format: :promise)}"
                  p.list-text = "募集締切: #{l(promise.limit_time, format: :promise)}"
          = link_to 'すべての待ち合わせをみる', promises_path
      .panel.panel-default
        .panel-heading
          span 応募
          div.move-right
            = link_to "主催", participants_path, { name: "my", remote: true, class: 'btn btn-sm btn-primary' }
            = link_to "参加", participants_path, { name: "your", remote: true, class: 'btn btn-sm btn-warning mgl-10' }
        .panel-body#participants_list
          = render partial: 'participants/list', locals: { promises: @promises }


    
  
  